[project]
name = "bolt-api"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.8",
    "django-bolt",
]

[tool.uv.sources]
django-bolt = { path = "./django-bolt", editable = true }
